management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    datasource:
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
            maximumPoolSize: 5
            minimumIdle: 5
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    output:
        ansi:
            enabled: ALWAYS
